//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPCamera
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IpCamerasEntities : DbContext
    {
        public IpCamerasEntities()
            : base("name=IpCamerasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmailSender> EmailSenders { get; set; }
        public virtual DbSet<FilesDir> FilesDirs { get; set; }
        public virtual DbSet<FilesFormat> FilesFormats { get; set; }
        public virtual DbSet<MyCamera> MyCameras { get; set; }
        public virtual DbSet<SM> SMS { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
