//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPCamera
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyCamera
    {
        public string Id { get; set; }
        public string urls { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int fps { get; set; }
        public string net_stream_port { get; set; }
        public string net_stream_prefix { get; set; }
        public Nullable<bool> net_stream { get; set; }
        public bool Face_Detection { get; set; }
        public bool Face_Recognition { get; set; }
        public int Brightness { get; set; }
        public int Contrast { get; set; }
        public int Darkness { get; set; }
        public bool Recording { get; set; }
        public bool On_Move_Pic { get; set; }
        public bool On_Move_Rec { get; set; }
        public bool On_Move_SMS { get; set; }
        public bool On_Move_EMAIL { get; set; }
        public int Move_Sensitivity { get; set; }
        public string Up_req { get; set; }
        public string Down_req { get; set; }
        public string Left_req { get; set; }
        public string Right_req { get; set; }
        public bool isEsp32 { get; set; }
        public Nullable<int> Row { get; set; }
        public Nullable<int> Coll { get; set; }
        public Nullable<int> VideoIndex { get; set; }
    }
}
